# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-22 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20180121_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='followers',
            field=models.ManyToManyField(related_name='_image_followers_+', to='images.Image'),
        ),
        migrations.AddField(
            model_name='image',
            name='following',
            field=models.ManyToManyField(related_name='_image_following_+', to='images.Image'),
        ),
    ]
