# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-22 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20180122_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='image',
            name='following',
        ),
    ]
